#!/usr/bin/env python3
"""Rebuilds the React Bits catalog from the official shadcn registry.

The registry is fetched with curl (the system python has no root certificates):

    curl -sfL https://reactbits.dev/r/registry.json \
      | python3 react-bits-catalog.py > react-bits.md
"""
import json
import re
import sys
from collections import defaultdict

REGISTRY = "https://reactbits.dev/r/registry.json"

# Weight is the main selection criterion — it also decides gate item 08 (speed).
HEAVY = {"three", "@react-three/fiber", "@react-three/drei",
         "@react-three/postprocessing", "postprocessing", "maath", "face-api.js"}
MEDIUM = {"ogl", "gl-matrix", "matter-js"}

GROUPS = [
    ("No scene setup — CSS, GSAP, Motion",
     "First choice. Cheap by weight, does not break item 08."),
    ("WebGL via ogl / physics",
     "One per page, no more. Check the bundle weight before shipping."),
    ("Heavy 3D — three.js and friends",
     "Only if the user explicitly asked for 3D. It costs speed."),
]


def bucket(deps):
    if any(d in HEAVY for d in deps):
        return 2
    if any(d in MEDIUM for d in deps):
        return 1
    return 0


def main():
    if sys.stdin.isatty():
        sys.exit("pipe the registry to stdin: curl -sfL " + REGISTRY + " | python3 " + sys.argv[0])
    items = json.load(sys.stdin)["items"]

    # 4 variants per component (JS/TS × CSS/TW) — collapse into one by title
    comp = {}
    for i in items:
        deps = sorted(re.sub(r"@\^?[\d.].*$", "", d) for d in i.get("dependencies", []))
        comp.setdefault(i["title"], (i.get("description", ""), deps))

    groups = defaultdict(list)
    for title, (desc, deps) in comp.items():
        groups[bucket(deps)].append((title, desc, deps))

    out = [
        "# React Bits catalog\n",
        f"Generated by `react-bits-catalog.py` from {REGISTRY} — {len(comp)} components.\n",
        "Installed one at a time: `npx shadcn@latest add @react-bits/<Name>-TS-TW`",
        "(variant suffixes: `JS-CSS`, `JS-TW`, `TS-CSS`, `TS-TW`).\n",
    ]
    for b, (name, note) in enumerate(GROUPS):
        rows = sorted(groups[b])
        out.append(f"\n## {name} ({len(rows)})\n\n{note}\n")
        for title, desc, deps in rows:
            tail = " `" + " + ".join(deps) + "`" if deps else ""
            out.append(f"- **{title}** — {desc}{tail}")

    print("\n".join(out))
    print(f"\n{len(comp)} components total", file=sys.stderr)


if __name__ == "__main__":
    main()
